# -*- coding: utf-8 -*-
"""CSE422_Project(employee_attrition_analysis).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ojmnomCjcSneb2-iw62GZ540TLA0zRwZ
"""

import numpy as np
import pandas as pd

employee = pd.read_csv("/content/employee attriation dataset.csv")

employee

df.dtypes

employee.isnull().sum()

emp_with_nulls = employee.copy()

nan_fraction = 0.03
n_nan = int(nan_fraction * emp_with_nulls.size)

row_indices = np.random.randint(0, emp_with_nulls.shape[0], n_nan)
col_indices = np.random.randint(0, emp_with_nulls.shape[1], n_nan)

for r, c in zip(row_indices, col_indices):
  if c != emp_with_nulls.shape[1]-1:
    emp_with_nulls.iat[r, c] = np.nan

emp_with_nulls.to_csv("employee_attrition_with_nulls.csv", index=False)

print("New dataset saved as employee_attrition_with_nulls.csv")

emp = pd.read_csv("/content/employee_attrition_with_nulls.csv")
emp

emp.isnull().sum()

print(emp.size)
var = emp.isnull().any(axis=1).sum()
print(var)

emp.info()

print(emp['EmployeeCount'].unique())

emp = emp.drop(columns=['EmployeeCount'])

emp

drop_cols = ['YearsAtCompany', 'MonthlyIncome', 'PerformanceRating', 'YearsSinceLastPromotion']

emp =emp.dropna(subset=drop_cols)

impute_cols = ['Age', 'DailyRate', 'DistanceFromHome', 'Education', 'HourlyRate', 'JobLevel',
               'MonthlyRate', 'NumCompaniesWorked', 'PercentSalaryHike', 'StockOptionLevel',
               'TotalWorkingYears', 'TrainingTimesLastYear', 'YearsInCurrentRole', 'YearsWithCurrManager']


for col in impute_cols:
    emp[col].fillna(emp[col].mean(), inplace=True)

print(emp.isna().sum())

emp =emp.drop("id",axis=1)

emp= emp.drop("StandardHours", axis=1)
emp = emp.drop("Over18",axis=1)

df.info()

mode_cols = ['BusinessTravel', 'Department', 'EducationField', 'EnvironmentSatisfaction',
             'Gender', 'JobInvolvement', 'JobRole', 'JobSatisfaction',
             'MaritalStatus', 'OverTime', 'RelationshipSatisfaction', 'WorkLifeBalance']

for col in mode_cols:
    emp[col].fillna(emp[col].mode()[0], inplace=True)

print(emp.isna().sum())

employee

employee =employee.drop("EmployeeCount",axis=1)

employee.info()

print(employee['Over18'].unique())

employee =employee.drop("Over18",axis=1)

unique_count = employee['StockOptionLevel'].nunique()
print(unique_count)

from sklearn.preprocessing import LabelEncoder

label_cols = ['BusinessTravel', 'OverTime']

le = LabelEncoder()
for col in label_cols:
    employee[col] = le.fit_transform(employee[col])

employee



cols_to_restore = ['Department', 'EducationField', 'Gender', 'JobRole', 'MaritalStatus']
employee_original = pd.read_csv("/content/employee attriation dataset.csv")
for col in cols_to_restore:
    employee[col] = employee_original[col]

# Verify
print(employee[cols_to_restore].head())

emp = employee_original.copy()

emp.size



employee = employee_original.copy()

employee.head()

employee.drop('Over18',axis=1)

employee =employee.drop("EmployeeCount",axis=1)

label_cols = ['BusinessTravel', 'OverTime']

le = LabelEncoder()
for col in label_cols:
    employee[col] = le.fit_transform(employee[col])



onehot_cols = ['Department', 'EducationField','Gender', 'JobRole', 'MaritalStatus']

employee = pd.get_dummies(employee, columns=onehot_cols)


print(employee.head())
print(employee.shape)

employee.info()

employee

employee = employee.drop('StandardHours',axis=1)

employee.info()

print ('Shape of the dataset is {}. This dataset contains {} rows and {} columns.'.format(employee.shape,employee.shape[0],employee.shape[1]))

##Selecting numerical features
numerical_data = employee.select_dtypes(include='number')

#append the features of numerical_data to list
numerical_features=numerical_data.columns.tolist()

print(f'There are {len(numerical_features)} numerical features:', '\n')
print(numerical_features)

#Selecting categoricalfeatures
categorical_data=employee.select_dtypes(include= 'object')

#append the features of categorical_data to list
categorical_features=categorical_data.columns.tolist()

print(f'There are {len(categorical_features)} categorical features:', '\n')
print(categorical_features)

"""Correlation of all the features (input and output features)"""

from sklearn.preprocessing import LabelEncoder

emp_encoded = emp.copy()
for col in emp_encoded.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    emp_encoded[col] = le.fit_transform(emp_encoded[col])

corr_matrix = emp_encoded.corr()

emp_encoded

emp.info()

import seaborn as sns
import matplotlib.pyplot as plt



# Your heatmap code
plt.figure(figsize=(18,14))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.3f', linewidths=0.3)
plt.title('Correlation Matrix Heatmap')
plt.tight_layout()  # Optional: helps with label spacing
plt.show()

"""BALANCE OR IMBALANCE CHECK"""

class_counts = emp['Attrition'].value_counts()

print(class_counts)  # just to see numbers in console

# Bar chart
plt.figure(figsize=(6,4))
sns.barplot(x=class_counts.index, y=class_counts.values, hue=class_counts.index,palette="viridis")

plt.title("Class Distribution of Attrition")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

numerical_data.describe().T

categorical_data.describe().T #boolean in that case

numerical_data.var()

employee

corr_matrix = employee.corr()
print(corr_matrix)

import seaborn as sns
import matplotlib.pyplot as plt



# Your heatmap code
plt.figure(figsize=(25,25))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.3f', linewidths=0.3)
plt.title('Correlation Matrix Heatmap')
plt.tight_layout()  # Optional: helps with label spacing
plt.show()

employee = employee.drop('Department_Human Resources',axis=1)
employee = employee.drop('JobRole_Sales Executive',axis=1)
employee = employee.drop('MonthlyIncome',axis=1)

employee.info()

corr_matrix = employee.corr()
# Your heatmap code
plt.figure(figsize=(25,25))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.3f', linewidths=0.3)
plt.title('Correlation Matrix Heatmap')
plt.tight_layout()  # Optional: helps with label spacing
plt.show()

employee.info()

from sklearn.model_selection import train_test_split
X = employee.drop('Attrition', axis=1)
y = employee['Attrition']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

# Features that need scaling (the ones with very different scales)
features_to_scale = ['MonthlyRate', 'DailyRate', 'HourlyRate']

# Fit scaler on training data only
scaler.fit(X_train[features_to_scale])

# Transform both training and test sets
X_train[features_to_scale] = scaler.transform(X_train[features_to_scale])
X_test[features_to_scale] = scaler.transform(X_test[features_to_scale])

# Identify and convert only boolean columns
X_train_df = X_train.copy()
Y_train_df = y_train.copy()
bool_columns = X_train_df.select_dtypes(include=['bool']).columns
X_train_df[bool_columns] = X_train_df[bool_columns].astype(int)

# Create scatter matrix
pd.plotting.scatter_matrix(X_train_df,
                          c=Y_train_df,
                          figsize=(20, 20),
                          marker='o',
                          hist_kwds={'bins': 20},
                          s=60,
                          alpha=.8,
                          cmap='coolwarm')
plt.show()



from sklearn.linear_model import LogisticRegression

# Default max_iter is usually 100, try increasing it
lr_models = []
iterations = [100, 500, 1000, 2000, 5000]

for max_iter in iterations:
    lr = LogisticRegression(max_iter=max_iter, random_state=42)
    lr.fit(X_train, y_train)
    accuracy = lr.score(X_test, y_test)
    print(f"Logistic Regression (max_iter={max_iter}): {accuracy:.4f}")

"""Logistic Regression"""

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report


logreg = LogisticRegression(random_state=42)
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)

print(f"Accuracy: {accuracy_score(y_test, y_pred)}")
print(classification_report(y_test, y_pred))

employee = pd.read_csv('/content/employeeds.csv')

files.download('/var/tmp/.ipynb_checkpoints/Y_train.csv')

import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import KFold, cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
import seaborn as sns

plt.hist(employee["Attrition"], bins=5, color='skyblue', edgecolor='black')
plt.title("Distribution of Attrition")
plt.xlabel("Value")
plt.ylabel("Frequency")
plt.show()

X = employee.drop('Attrition', axis=1)
y = employee['Attrition']

X.info()

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

import pandas as pd

# Find binary columns
binary_cols = [col for col in X.columns if set(X[col].unique()) <= {0, 1}]
print("Binary Columns:", binary_cols)

"""NN

3 Layer Nn
"""

from sklearn.model_selection import KFold
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

# Assuming X_scaled and y are already prepared
kf = KFold(n_splits=5, shuffle=True, random_state=42)
model = MLPClassifier(hidden_layer_sizes=(32,16,8), activation='relu', solver='adam', max_iter=500, random_state=42)

accuracies = []
conf_matrices = []
fold = 1

for train_index, test_index in kf.split(X_scaled):
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Train Neural Network
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Accuracy
    acc = accuracy_score(y_test, y_pred)
    accuracies.append(acc)

    # Confusion matrix
    conf_matrices.append(confusion_matrix(y_test, y_pred))

    print(f"Fold {fold} Accuracy: {acc:.4f}")
    fold += 1

print(f"Mean Accuracy: {np.mean(accuracies):.4f}")



from sklearn.model_selection import KFold
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import roc_curve, auc, accuracy_score, confusion_matrix
import numpy as np

# Assuming X_scaled and y are already prepared
kf = KFold(n_splits=5, shuffle=True, random_state=42)
model = MLPClassifier(hidden_layer_sizes=(32,16), activation='relu', solver='adam', max_iter=500, random_state=42)

accuracies = []
conf_matrices = []
fold = 1
fold_data_nn = []
for train_index, test_index in kf.split(X_scaled):
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Train Neural Network
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]
    # Accuracy
    acc = accuracy_score(y_test, y_pred)
    accuracies.append(acc)

    # Confusion matrix
    conf_matrices.append(confusion_matrix(y_test, y_pred))
    fpr, tpr, thresholds = roc_curve(y_test, y_proba)
    roc_auc = auc(fpr, tpr)
    fold_data_nn.append({
        "fold": fold,
        "accuracy": acc,
        "roc_auc": roc_auc,
        "fpr": fpr,
        "tpr": tpr,
        "thresholds": thresholds,
        "y_test": y_test,
        "y_pred": y_pred
    })
    print(f"Fold {fold} Accuracy: {acc:.4f}")
    fold += 1

print(f"Mean Accuracy: {np.mean(accuracies):.4f}")

plt.figure(figsize=(5,6))
sns.heatmap(conf_matrices[-1], annot=True, fmt='d', cmap='Blues',
            xticklabels=target_names, yticklabels=target_names)
plt.title("Confusion Matrix (Last Fold)")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

from sklearn.neighbors import KNeighborsClassifier


kf = KFold(n_splits=5, shuffle=True, random_state=42)
model = KNeighborsClassifier(n_neighbors=3)  # choose k
accuracies = []
conf_matrices = []
fold = 1
fold_data_KNN=[]
for train_index, test_index in kf.split(X_scaled):
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Train KNN
    model.fit(X_train, y_train)


    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]

    acc = accuracy_score(y_test, y_pred)
    fpr, tpr, thresholds = roc_curve(y_test, y_proba)
    roc_auc = auc(fpr, tpr)
    fold_data_KNN.append({
        "fold": fold,
        "accuracy": acc,
        "roc_auc": roc_auc,
        "fpr": fpr,
        "tpr": tpr,
        "thresholds": thresholds,
        "y_test": y_test,
        "y_pred": y_pred
    })
    conf_matrices.append(confusion_matrix(y_test, y_pred))
    accuracies.append(acc)
    print(f"Fold {fold} Accuracy: {acc:.4f}")
    fold += 1

print(f"Mean Accuracy: {sum(accuracies)/len(accuracies):.4f}")



plt.figure(figsize=(5,6))
sns.heatmap(conf_matrices[-1], annot=True, fmt='d', cmap='Blues',
            xticklabels=target_names, yticklabels=target_names)
plt.title("Confusion Matrix (Last Fold)")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

kf = KFold(n_splits=5, shuffle=True, random_state=42)
model = LogisticRegression(max_iter=1000)

fold = 1
accuracies = []
conf_matrices = []
fold_data_LR = []

for train_index, test_index in kf.split(X_scaled):
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Train model
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)
    y_proba = model.predict_proba(X_test)[:, 1]
    # Accuracy
    acc = accuracy_score(y_test, y_pred)
    accuracies.append(acc)
    fpr, tpr, thresholds = roc_curve(y_test, y_proba)
    roc_auc = auc(fpr, tpr)
    # Confusion matrix
    fold_data_LR.append({
        "fold": fold,
        "accuracy": acc,
        "roc_auc": roc_auc,
        "fpr": fpr,
        "tpr": tpr,
        "thresholds": thresholds,
        "y_test": y_test,
        "y_pred": y_pred
    })
    conf_matrices.append(confusion_matrix(y_test, y_pred))

    print(f"Fold {fold} Accuracy: {acc:.4f}")
    fold += 1

print(f"\nAverage Accuracy: {np.mean(accuracies):.4f}")

target_names = employee['Attrition'].unique().tolist()

plt.figure(figsize=(5,6))
sns.heatmap(conf_matrices[-2], annot=True, fmt='d', cmap='Blues',
            xticklabels=target_names, yticklabels=target_names)
plt.title("Confusion Matrix (4th fold)")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

employee

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

# Find numeric columns
numeric_cols = X.select_dtypes(include=['int64', 'float64']).columns

# Remove binary columns from numeric list
numeric_to_scale = list(set(numeric_cols) - set(binary_cols))

# Column transformer: scale numeric, pass through binary as-is
ct = ColumnTransformer(
    transformers=[
        ("scale_numeric", StandardScaler(), numeric_to_scale)
    ],
    remainder="passthrough"  # keep other columns (binary) unchanged
)

X_scaled = ct.fit_transform(X)

from sklearn.neighbors import KNeighborsClassifier


kf = KFold(n_splits=5, shuffle=True, random_state=42)
model = KNeighborsClassifier(n_neighbors=3)  # choose k
accuracies = []
conf_matrices = []
fold = 1

for train_index, test_index in kf.split(X_scaled):
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Train KNN
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Accuracy
    acc = accuracy_score(y_test, y_pred)
    accuracies.append(acc)

    # Confusion matrix
    conf_matrices.append(confusion_matrix(y_test, y_pred))

    print(f"Fold {fold} Accuracy: {acc:.4f}")
    fold += 1

print(f"Mean Accuracy: {sum(accuracies)/len(accuracies):.4f}")

"""logistic with binary classes unscaled

"""

kf = KFold(n_splits=5, shuffle=True, random_state=42)
model = LogisticRegression(max_iter=1000)

fold = 1
accuracies = []
conf_matrices = []

for train_index, test_index in kf.split(X_scaled):
    X_train, X_test = X_scaled[train_index], X_scaled[test_index]
    y_train, y_test = y[train_index], y[test_index]

    # Train model
    model.fit(X_train, y_train)

    # Predict
    y_pred = model.predict(X_test)

    # Accuracy
    acc = accuracy_score(y_test, y_pred)
    accuracies.append(acc)

    # Confusion matrix
    conf_matrices.append(confusion_matrix(y_test, y_pred))

    print(f"Fold {fold} Accuracy: {acc:.4f}")
    fold += 1

print(f"\nAverage Accuracy: {np.mean(accuracies):.4f}")

employee

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA()
pca.fit(employee)

# Plot explained variance ratio
plt.plot(range(1, len(pca.explained_variance_ratio_)+1), pca.explained_variance_ratio_.cumsum(), marker='o')
plt.xlabel("Number of Components")
plt.ylabel("Cumulative Explained Variance")
plt.title("PCA Explained Variance")
plt.grid()
plt.show()

emp = employee.copy()

numeric_cols = emp.select_dtypes(include=['float64', 'int64']).columns
binary_cols = [col for col in numeric_cols if set(emp[col].unique()) <= {0, 1}]

# Remove binary columns from numeric ones
numeric_cols = [col for col in numeric_cols if col not in binary_cols]

# Scale numeric columns
scaler = StandardScaler()
emp_scaled_numeric = scaler.fit_transform(emp[numeric_cols])

# Combine scaled numeric + original binary
emp_scaled_df = pd.DataFrame(emp_scaled_numeric, columns=numeric_cols)
for col in binary_cols:
    emp_scaled_df[col] = emp[col].values

emp_scaled_df

from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

pca = PCA()
pca.fit(emp_scaled_df)

# Plot explained variance ratio
plt.plot(range(1, len(pca.explained_variance_ratio_)+1), pca.explained_variance_ratio_.cumsum(), marker='o')
plt.xlabel("Number of Components")
plt.ylabel("Cumulative Explained Variance")
plt.title("PCA Explained Variance")
plt.grid()
plt.show()

from sklearn.decomposition import PCA
import numpy as np

pca = PCA().fit(emp_scaled_df)  # X_scaled: numeric features scaled; binaries either excluded or passthrough
cumvar = np.cumsum(pca.explained_variance_ratio_)
n90 = np.argmax(cumvar >= 0.90) + 1
n95 = np.argmax(cumvar >= 0.95) + 1
print("PCs for 90%:", n90, " | PCs for 95%:", n95)

pip install kneed

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

wcss = []
k_range = range(1, 11)

for k in k_range:
    kmeans = KMeans(n_clusters=k, random_state=42, n_init=10)
    kmeans.fit(emp_scaled_df)        # <-- fit KMeans to your data
    wcss.append(kmeans.inertia_)    # <-- this is the WCSS

wcss

from kneed import KneeLocator

# Use KneeLocator on WCSS values
kneedle = KneeLocator(
    k_range,
    wcss,
    curve='convex',  # WCSS curve is convex
    direction='decreasing'  # WCSS decreases as k increases
)

elbow_k = kneedle.knee
print(f"\n📌 Suggested optimal k (KneeLocator): {elbow_k}")

# (Optional) visualize the detected elbow
plt.figure(figsize=(10, 6))
plt.plot(k_range, wcss, marker='o')
plt.axvline(elbow_k, color='red', linestyle='--', label=f"Elbow k={elbow_k}")
plt.title("WCSS vs k (Elbow Found by KneeLocator)")
plt.xlabel("Number of Clusters")
plt.ylabel("WCSS")
plt.legend()
plt.grid()
plt.show()

from sklearn.decomposition import PCA

# Reduce to 19 components
pca = PCA(n_components=19, random_state=42)
X_pca = pca.fit_transform(emp_scaled_df)

# Use your scaled or PCA-transformed data
X_clustering = X_pca  # or X_scaled if not using PCA

final_kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
cluster_labels = final_kmeans.fit_predict(X_clustering)

# Optional: check cluster sizes
import numpy as np
print("Cluster distribution:", np.bincount(cluster_labels))

len(cluster_labels)

# Reduce to 2D for plotting
pca_2d = PCA(n_components=2)
X_2d = pca_2d.fit_transform(X_clustering)

plt.figure(figsize=(8,6))
plt.scatter(X_2d[:,0], X_2d[:,1], c=cluster_labels, cmap='viridis', alpha=0.6)
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("K-Means Clusters (k=4)")
plt.colorbar(label="Cluster")
plt.show()

best_LR = max(fold_data_LR, key=lambda x: x["roc_auc"])
best_NN = max(fold_data_nn, key=lambda x: x["roc_auc"])
best_KNN = max(fold_data_KNN, key=lambda x: x["roc_auc"])

print("Best Logistic Regression Fold:", best_LR["fold"], "AUC:", best_LR["roc_auc"])
print("Best Neural Network Fold:", best_NN["fold"], "AUC:", best_NN["roc_auc"])
print("Best KNN Fold:", best_KNN["fold"], "AUC:", best_KNN["roc_auc"])

import matplotlib.pyplot as plt

plt.figure(figsize=(8,6))
plt.plot(best_LR['fpr'], best_LR['tpr'], label=f"LR (AUC={best_LR['roc_auc']:.2f})")
plt.plot(best_NN['fpr'], best_NN['tpr'], label=f"NN (AUC={best_NN['roc_auc']:.2f})")
plt.plot(best_KNN['fpr'], best_KNN['tpr'], label=f"KNN (AUC={best_KNN['roc_auc']:.2f})")
plt.plot([0,1], [0,1], 'k--')
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC Curve Comparison (Best Fold Each Model)")
plt.legend()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix

# Example: Get confusion matrices for the best folds
cm_LR = confusion_matrix(best_LR['y_test'], best_LR['y_pred'])
cm_NN = confusion_matrix(best_NN['y_test'], best_NN['y_pred'])
cm_KNN = confusion_matrix(best_KNN['y_test'], best_KNN['y_pred'])

# Plot them side by side (all blue)
fig, axes = plt.subplots(1, 3, figsize=(15, 4))

sns.heatmap(cm_LR, annot=True, fmt="d", cmap="Blues", ax=axes[0], cbar=False)
axes[0].set_title("Logistic Regression")

sns.heatmap(cm_NN, annot=True, fmt="d", cmap="Blues", ax=axes[1], cbar=False)
axes[1].set_title("Neural Network")
axes[1].set_ylabel("")  # Remove extra y-label

sns.heatmap(cm_KNN, annot=True, fmt="d", cmap="Blues", ax=axes[2], cbar=False)
axes[2].set_title("KNN")
axes[2].set_ylabel("")  # Remove extra y-label

plt.suptitle("Confusion Matrix Comparison (Best Fold Each Model)", fontsize=14)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt

models = ["NN", "KNN", "LR"]
acc = [0.8629, 0.8640, 0.8849]

plt.bar(models, acc, color=['#2ca02c','#ff7f0e','#1f77b4'])
plt.ylim(0,1)
for i,v in enumerate(acc): plt.text(i,v+0.01,f"{v:.4f}",ha='center')
plt.show()

import matplotlib.pyplot as plt
import numpy as np

# Precision and recall values
models = ["NN","KNN","LR"]
precision = [11/(11+14), 3/(3+8), 12/(12+4)]  # tp/(tp+fp)
recall = [11/(11+25), 3/(3+33), 12/(12+30)]   # tp/(tp+fn)

x = np.arange(len(models))
width = 0.35

plt.bar(x - width/2, precision, width, label="Precision", color="#1f77b4")
plt.bar(x + width/2, recall, width, label="Recall", color="#ff7f0e")
plt.xticks(x, models)
plt.ylim(0,1)
plt.title("Precision vs Recall Comparison")
plt.legend()
plt.show()